version: '3.8'
name: ${CONTAINER_NAME}
services:
  dev:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${PWD}:${CONTAINER_WORKDIR}
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig
      - ~/.ssh:/home/${USERNAME}/.ssh
    stdin_open: true
    tty: true
    networks:
      - ${CONTAINER_NAME}
    labels:
      - "com.dockit=true"
      - "com.dockit.project=${CONTAINER_NAME}"

networks:
  ${CONTAINER_NAME}:
    name: ${CONTAINER_NAME}
    driver: bridge 